just_reviews/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from reviews import views
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^reviews/', include('reviews.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.conf.urls import url
from django.contrib import admin
from reviews import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_product', views.add_product, name='add_product'),
    url(r'^details/(?P<product_slug>[\w\-]+)/$', views.product_detail, name='product_detail'),
    url(r'^search', views.search_product, name='search'),
    url(r'^add_comment/(?P<product_slug>[\w\-]+)/(?P<user_id>[\w\-]+)/$', views.add_comment, name='add_comment'),
    url(r'^was_added', views.was_added, name='was_added'),
    url(r'^back_comment/(?P<comment_id>[\w\-]+)/(?P<username>[\w\-]+)/$', views.back_comment, name='back_comment'),
    url(r'^thumbs_up/(?P<product_slug>[\w\-]+)/(?P<username>[\w\-]+)/$', views.thumbsUp, name='thumbsUp'),
    url(r'^thumbs_down/(?P<product_slug>[\w\-]+)/(?P<username>[\w\-]+)/$', views.thumbsDown, name='thumbsDown'),
    url(r'^profile_view/(?P<username>[\w\-]+)/$', views.profile_view, name='profile_view'),
    url(r'^view_user/(?P<username>[\w\-]+)/$', views.view_user, name='view_user'),
    url(r'^messenger/(?P<sender>[\w\-]+)/(?P<reciever>[\w\-]+)/(?P<body>[\a-z\d\-]+)/$', views.messenger, name='messenger'),
    url(r'^signin/$', views.signin),
    url(r'^signup/$', views.signup ),
    url(r'^signout/$', auth_views.logout, {'template_name': 'reviews/index.html'}),
    url(r'^check_message/(?P<username>[\w\-]+)/$', views.messagify, name='messagify'),
]

reviews/models.py
import time
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):  #For Python 2, use __str__ on Python 3
        return self.name


class Product(models.Model):
    name            = models.CharField(max_length=30,unique=True) # Should a product name be unique?? possible???(yes sir i do think product uniqueness is useful.
    views           = models.IntegerField(default=0)
    details         = models.CharField(max_length=100)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null = True)
    categorysaver   = models.CharField(max_length=100, null=True, blank=True)
    thumbsUp        = models.IntegerField(default=0)
    thumbsDown      = models.IntegerField(default=0)
    slug            = models.SlugField(blank=True,unique=True)
    comments        = models.IntegerField(default=0)
    pub_date        = models.DateField(auto_now=True, blank=True)
    added           = models.FloatField(default=time.time(), null=True, blank=True) # Can we use models.DateTimeField here instead?(oh its because i collect the time in seconds(integer(time.time())) and use it for some javascript calculations on the front end to determine "how long" for activities, and i am not sure what format dateField 
    image           = models.FileField(upload_to='product-imgs/',null=True, blank=True)
    thumbsUpBy      = models.CharField(max_length=10000, default = "test", null=True, blank=True)
    thumbsDownBy    = models.CharField(max_length=10000, default = "test", null=True, blank=True)
    posted_by       = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null = True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):              # __unicode__ on Python 2
        return self.name

    class Meta:
        ordering = ('name',)


class Comment(models.Model):
    title       = models.CharField(max_length=100)
    body        = models.TextField(max_length=200)
    pub_date    = models.DateField(auto_now=True, blank=True)
    added       = models.IntegerField(default=time.time(),  blank=True)# Can we use models.DateTimeField here instead?(oh its because i collect the time in seconds(integer(time.time())) and use it for some javascript calculations on the front end to determine "how long" for activities, and i am not sure what format dateField accepts.
    image       = models.FileField(upload_to='comment-imgs/',null=True, blank=True)
    backs       = models.IntegerField(default=0)
    backedBy    = models.CharField(max_length=10000, default = "test", null=True, blank=True) # Sounds like this should be a related field to a User or a UserAccount object(thanks sir i will change this)
    product     = models.ForeignKey(Product, on_delete=models.CASCADE)
    comment_product_slug = models.CharField(max_length=100, null=True, blank=True)
    posted_by   = models.ForeignKey( User, on_delete=models.CASCADE, blank=True, null = True)

    def __str__(self):              # __unicode__ on Python 2
        return self.title

    class Meta:
        ordering = ('title',)
# Create your models here.

class UserAccount(models.Model):
    User        = models.OneToOneField(User, on_delete=models.CASCADE, related_name = "user")
    image       = models.FileField(upload_to='profile-imgs/',null=True, blank=True)
    joined      = models.IntegerField(default=time.time(),  blank=True)# Can we use models.DateTimeField here instead?(oh its because i collect the time in seconds(integer(time.time())) and use it for some javascript calculations on the front end to determine "how long" for activities, and i am not sure what format dateField 

    def __str__(self):
        return self.User.username

    class Meta:
        verbose_name_plural = 'User Accounts'

class Message(models.Model):
    sent_to        = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "message_to")
    sent_from      = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "message_from")
    body           = models.TextField(max_length=200)
    created        = models.IntegerField(default=time.time(),  blank=True)# Can we use models.DateTimeField here instead? (oh its because i collect the time in seconds(integer(time.time())) and use it for some javascript calculations on the front end to determine "how long" for activities, and i am not sure what format dateField 

    def __str__(self):
        return self.sent_from.username

reviews/forms.py
from django import forms
from django.contrib.auth.models import User
from reviews.models import Category, Comment, Product, UserAccount,Message


class CategoryForm(forms.ModelForm):


    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")

    class Meta:
        # Provide an association between the ModelForm and a model
        model  =  Category
        fields = ('name',)

class ProductForm(forms.ModelForm):

    name         = forms.CharField(max_length=30,
                                   help_text="Name     ::")
    details      = forms.CharField(max_length=300,
                                   help_text="Details :")
    views        = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    thumbsUp     = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    thumbsDown   = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug         = forms.CharField(widget=forms.HiddenInput(), required=False)
    Comment      = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    image        = forms.FileField(required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model   = Product
        fields  = ('name' ,'details', 'image',)

class CommentForm(forms.ModelForm):

    title       = forms.CharField(max_length=128, help_text="Enter Title :: ")

    body        = forms.CharField(max_length=300, help_text="Comment ::")

    image       = forms.FileField(required=False)

    
    class Meta:
        # Provide an association between the ModelForm and a model

        model = Comment

        fields  = ('title','body','image')

class SearchForm(forms.ModelForm):
    name   = forms.CharField(max_length=128,
                            help_text="Please enter product name.")

    class Meta:
        # Provide an association between the ModelForm and a model
        model   = Product
        fields  = ('name',)
    
class UserRegistrationForm(forms.ModelForm):
    username    = forms.CharField(max_length=256, widget=forms.TextInput(), help_text="UserName     ::")
    first_name  = forms.CharField(max_length=256, help_text="First name     ::")
    last_name   = forms.CharField(max_length=256, help_text="Last name     ::")
    email       = forms.CharField(max_length=256, widget=forms.EmailInput(), help_text="Email addr    ::")
    password    = forms.CharField(max_length=256, widget=forms.PasswordInput(), help_text="Password    ::")
    image       = forms.FileField(required=False)

    class Meta:
        model = UserAccount
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'image')

class Signinform(forms.ModelForm):
    username   =   forms.CharField(max_length=256, widget=forms.EmailInput())
    password=   forms.CharField(max_length=256, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields= ('username','password' )

class UserEditForm(forms.ModelForm):
    username    = forms.CharField(max_length=256, widget=forms.TextInput(), help_text="UserName     ::", required=False)
    first_name  = forms.CharField(max_length=256, help_text="First name     ::", required=False)
    last_name   = forms.CharField(max_length=256, help_text="Last name     ::", required=False)
    email       = forms.CharField(max_length=256, widget=forms.EmailInput(), help_text="Email addr    ::", required=False)
    password    = forms.CharField(max_length=256, widget=forms.PasswordInput(), help_text="Password    ::", required=False)
    image       = forms.FileField(required=False)

    class Meta:
        model = UserAccount
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'image')

class MessageForm(forms.ModelForm):
    body    = forms.CharField(max_length=256,help_text="body     ::", widget=forms.TextInput(), required=False)
    
    

    class Meta:
        model = Message
        fields = ('body',)

templates/reviews/add_product.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="en">

<head>
    <title>Just-Reviews</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "reviews/assets/plugins/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "reviews/assets/css/main.css" %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <body onload="addtime();">

        
        <header class="head">

            <div class="page-header">
                <div class="topmost__box-sign-up">
                    <a href="/reviews/">
                        <h1>  Just-Reviews
                            <small>
                                <br> 
                                <h2>
                                    No. 1 reviews landing in Nigeria
                                </h2>
                            </small>
                        </h1>
                    </a>

                    <div class="authenthication pull-right">
                    
                {% if user.is_authenticated %}
                        <a href="#" class="sign-up usernameref">
                            <button class="btn btn-primary first-button">Welcome {{user.username}}</button>
                        </a>
                        <a href="/reviews/signout" class="sign-in">
                            <button class="btn btn-primary second-button">Sign-out</button>
                        </a>

                {% else %}

                        <a href="/reviews/signup" class="sign-up">
                                <button class="btn btn-primary first-button">Sign up</button>
                        </a>
                        <a href="/reviews/signin" class="sign-in">
                            <button class="btn btn-primary second-button">Sign-in</button>
                        </a>
                    
                {% endif %}

                    <div class="pic " style="position:relative; top:110%; left:-22%;" >

                        <a href="#">
                            <div class="avatar pull-right" >
                            <img style=" border-radius:20%; height:60px; width:60px;" src={% if user.user.image %}"  {{user.user.image.url|default_if_none:'#'}}  "{% endif %} alt="image here"33   qaE\`w                                                          \>
                            </div>
                        </a>
                    </div>
                    </div>
                </div>
                <div>
                    
                    
                    <form id="SearchForm" method="get" action="/reviews/search/"
                    enctype="multipart/form-data">
                    
                    <div class="input-group">
                        
                        
                        <input class="form-control" placeholder="Product" type="text" name="name" maxlength="128" required id="id_name" />
                        
                        <span class="input-group-btn">
                            <input class="btn btn-primary" type="submit" name="submit" value="Search" />
                        </span>
                        
                    </div>

                    </form>
                    
                </div>
            </div>


        </header>
        <div class="container ">

            

            <main>
                <!---review AD-->

               
        
                <!---review AD-->
                <hr>
                <!---reviews display-->
                <div class="first-container">
                <div class="trending">
                    <p>
                        <span>
                            <h3>
                                New Product
                            </h3>
                            
                        </span>

                    </p>
                </div>

                <div class="container2">
                                
                        <div class="container2">
                            <div class="row" style="display:flex; color :rgb(148, 148, 148); padding-top:10px; justify-content:center; box-shadow: 0px 1px 2px #888888;">
                               
                                <form method="POST" action="/reviews/add_product/" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <p>
                                            <select class="form-control" name="category" id="">
                                                <option value="general">Category</option>
                                                {% for options in categories %}
                                                <option value="{{ options.name }}">{{ options.name }}</option>
                                                {% endfor %}    
                                            </select>      
                                        </p>   
                                        {% for hidden in form.hidden_fields %}
                                        {{ hidden }} 
                                        {% endfor %}    
                                        <p>
        
                                            <input class="form-control" type="text" name="name" placeholder="Product Name" maxlength="50" required id="id_Product_name" />
                                        </p> 
        
                                        <p>
                                            <input class="form-control" type="text" name="details" placeholder="Description"  maxlength="300" required id="id_details_name" />
                                        
                                        </p>
                                        
                                        <p>
                                            Product image<input type="file" name="image" id="id_image"> 
                                        </p>
                                        
                                        <p>
                                            <button style="width:100%;" class="btn btn-primary" type="submit">Add Product to Just-Reviews</button>
                                        </p>
                                        
                                    </form>
                            
                        </div>
                        
                <!-- latest post ends here -->

            </main>

           
           <hr>
        </div>

        <footer>
            <div class="footer__container">
                
                <div class="right-side side__hold">
                    <div class="social-media">
                        <a href="#">
                            <img src="{% static "reviews/assets/img/icons/instagram.png" %}" alt="">
                            <span class="icon-username">
                                @Just-Reviews
                            </span>
                        </a>

                        <a href="#">
                            <img src="{% static "reviews/assets/img/icons/twitter.png" %}" alt="">
                            <span class="icon-username">
                                @Just-Reviews
                            </span>
                        </a>

                        <a href="#">
                            <img src="{% static "reviews/assets/img/icons/facebook.png" %}" alt="">
                            <span class="icon-username">
                                  . facebook.com/justreview
                            </span>
                        </a>
                    </div>
                    
                    <div >
                        <div class="address-bar">
                            <h4>Just-Reviews.NG </h4>
                        </div>
                        <div class="address-bar">
                            Lekki - Epe Expy, Ajah, Lagos, Nigeria
                        </div>
                    </div>

                </div>

            </div>
        </footer>

     

        
    <script src="{% static "reviews/assets/js/like.js" %}"></script>   
    </body>

</html>

templates/reviews/login.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="en">

<head>
    <title>Just-Reviews</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "reviews/assets/plugins/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "reviews/assets/css/main.css" %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <body onload="addtime();">

        
        <header class="head">
            
            <div class="page-header">
                <div class="topmost__box-sign-up">
                    <a href="/reviews/">
                        <h1>  Just-Reviews
                            <small>
                                <br> 
                                <h2>
                                    No. 1 reviews landing in Nigeria
                                </h2>
                            </small>
                        </h1>
                    </a>

                    <div class="authenthication pull-right">
                    
                {% if user.is_authenticated %}
                        <a href="#" class="sign-up usernameref">
                            <button class="btn btn-primary first-button">Hi {{user.username}}</button>
                        </a>
                        <a href="/reviews/signout" class="sign-in">
                            <button class="btn btn-primary second-button">Sign-out</button>
                        </a>

                {% else %}

                        <a href="/reviews/signup" class="sign-up">
                                <!-- <button class="btn btn-primary first-button">Sign up</button> -->
                        </a>
                        <a href="/reviews/signin" class="sign-in">
                            <!-- <button class="btn btn-primary second-button">Sign-in</button> -->
                        </a>
                    
                {% endif %}

                    <div class="pic " style="position:relative; top:110%; left:-22%;" >
                        
                        <a href="#">
                            <div class="avatar pull-right" >
                            <!-- <img style=" border-radius:20%; height:60px; width:60px;" src={% if user.user.image %}"  {{user.user.image.url|default_if_none:'#'}}  "{% endif %} alt="image here"> -->
                            </div>
                        </a>
                        
                    </div>
                    </div>
                </div>
                <div>
                    
                    
                    <form id="SearchForm" method="get" action="/reviews/search/"
                    enctype="multipart/form-data">
                    
                    <div class="input-group">
                        
                        
                        <input class="form-control" placeholder="Product" type="text" name="name" maxlength="128" required id="id_name" />
                        
                        <span class="input-group-btn">
                            <input class="btn btn-primary" type="submit" name="submit" value="Search" />
                        </span>
                        
                    </div>

                    </form>
                    
                </div>
            </div>


        </header>
        <div class="container ">

            

            <main>
                <!---review AD-->

                <div class="help-reviews">
                        <div>
                                <img src="{% static "reviews/assets/img/write_review.png" %}" alt="help-image">
                        </div>
    
                        <div class="u-space-l4">
                            <h2 class="alternate u-space-b3"><font face = "Comic sans MS" size =" 5">Join easy and start helping the Community today</font><br /></h2>
    
                            <p class="u-space-b3">
                                Find Just-reviews helpful? Start helping others by sharing your experience.
    
                            </p>
                            <a href="#" class="sign-up">
                                <!-- <button class="btn btn-primary first-button">Write a review now</button> -->
                            </a>
                            <a href="#" class="sign-up">
                                <!-- <button class="btn btn-primary first-button">Share a new product</button> -->
                            </a>
                        </div>
                    </div>
        
                <!---review AD-->
                <hr>
                <!---reviews display-->
                <div class="first-container">
                <div class="trending">
                    <p>
                        <span>
                            <h3>
                                LOGIN TO JUST REVIEWS
                            </h3>
                            
                        </span>

                    </p>
                </div>

                <div class="container2">
                        <hr>
                        
        
        
                        <div class="container2">
                            <div class="row" style="display:flex; color :rgb(148, 148, 148); padding-top:10px; justify-content:center; box-shadow: 0px 1px 2px #888888;">
                                <div class="container2 col-md-4" style="border-right: 1px solid rgb(202, 202, 202);">
                                    <p >
                                        <h3 style="display:flex; color :rgb(148, 148, 148);  justify-content:center;">Sign-in</h3>
                                    </p>
                                    <form method="POST" action="/reviews/signin/" >
                                        {% csrf_token %}
                                        <p>
                                            <input class="form-control" placeholder="Username" type="text" name="username">
                                        </p>
                                        <p>
                                            <input class="form-control" placeholder="Password" type="password" name="password">
                                        </p>
        
                                        <p>
                                            <button style="width:100%;" class="btn btn-primary" type="submit">Login</button>
                                        </p>
                                    </form>
                                </div>
                                <div class="container2 col-md-4" style="border-left: 1px solid rgb(226, 226, 226);" >
                                        <p >
                                            <h3 style="display:flex; color :rgb(148, 148, 148);  justify-content:center;">Sign-up</h3>
                                        </p>
                                    <form method="POST" action="/reviews/signup/" enctype="multipart/form-data">
                                        {% csrf_token %}                                
                                        <p>
        
                                            <input class="form-control" type="text" name="last_name" placeholder="Last Name" maxlength="10" required id="id_last_name" />
                                        </p> 
        
                                        <p>
                                            <input class="form-control" type="text" name="first_name" placeholder="First Name"  maxlength="10" required id="id_first_name" />
                                        
                                        </p>
                                        
                                        <p>
                                            <input class="form-control" type="text" name="username" placeholder="UserName"  maxlength="10" required id="id_username" />
                                        </p> 
                                        
                                        <p>
                                            <input class="form-control" type="email" name="email" placeholder="E-mail" maxlength="20" required id="id_email" />
                                        </p>
                                        
                                        <p>
                                            <input class="form-control pass_target" type="password" name="password" placeholder="Password" maxlength="256" required id="id_password" />
                                        </p> 
                                        
                                        <p>
                                            <input class="form-control pass_retype_target" type="password" name="password" placeholder="Retype Password" maxlength="256" required id="id_password" />
                                            <ul ><li class="mismatch" style="color: red">Password mismatch</li> <li class="match glyphicon glyphicon-check" style="color: rgb(0, 255, 21)"></li> </ul>
                                        </p>
        
                                        <p>
                                            Profile image<input type="file" name="image" id="id_image"> 
                                        </p>
                                        
                                        <p class="btn_target">
                                            <button style="width:100%;" class="btn btn-primary" type="submit">Add me to Just-Reviews</button>
                                        </p>
                                        
                                    </form>
                                    {% for error in error %} 
                                    <div style="color: red">
                                        {{error}}
                                    </div>
                                    {% endfor%}
                                </div>
                        </div>
                        
                <!-- latest post ends here -->

            </main>

           
           <hr>
        </div>

        <footer>
            <div class="footer__container">
                
                <div class="right-side side__hold">
                    <div class="social-media">
                        <a href="#">
                            <img src="{% static "reviews/assets/img/icons/instagram.png" %}" alt="">
                            <span class="icon-username">
                                @Just-Reviews
                            </span>
                        </a>

                        <a href="#">
                            <img src="{% static "reviews/assets/img/icons/twitter.png" %}" alt="">
                            <span class="icon-username">
                                @Just-Reviews
                            </span>
                        </a>

                        <a href="#">
                            <img src="{% static "reviews/assets/img/icons/facebook.png" %}" alt="">
                            <span class="icon-username">
                                  . facebook.com/justreview
                            </span>
                        </a>
                    </div>
                    
                    <div >
                        <div class="address-bar">
                            <h4>Just-Reviews.NG </h4>
                        </div>
                        <div class="address-bar">
                            Lekki - Epe Expy, Ajah, Lagos, Nigeria
                        </div>
                    </div>

                </div>

            </div>
        </footer>

     

        
    <script src="{% static "reviews/assets/js/like.js" %}"></script>   
    <script src="{% static "reviews/assets/js/passwordcheck.js" %}"></script>   
    </body>

</html>